# This is a basic workflow to help you get started with Actions

name: "SunshineCTF Challenge Validator"

description: "Validator for SunshineCTF challenges to ensure all administrative requirements of a challenge are met"

branding:
  icon: "check-circle"
  color: "yellow"

runs:
  using: "docker"
  image: "Dockerfile"
# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

#       # Runs a single command using the runners shell
#       - name: Run check script
#         run: |
#           pwd
#           ls -la
#           ls -la *
#           python3 check.py
