# This is a basic workflow to help you get started with Actions

name: "SunshineCTF Challenge Validator"

description: "Validator for SunshineCTF challenges to ensure all administrative requirements of a challenge are met"

branding:
  icon: "check-circle"
  color: "yellow"

runs:
  using: "docker"
  image: "Dockerfile"
