name: Test Challenge Validator

on:
  workflow_dispatch:
  push:
    branches: [ main, issue/7/single-challenge-repo ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install pytest
      run: pip install pytest
    
    - name: Run tests
      run: pytest test_check.py -v
    
    - name: Test monorepo mode
      uses: ./
      with:
        monorepo: 'true'
    
    - name: Test single challenge mode
      run: |
        cp -r test/web/flag-vault-1/* .
        
    - name: Test single challenge mode action
      uses: ./
      with:
        monorepo: 'false'